/*
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.extension.db.internal.operation;

import org.mule.extension.db.api.param.QueryDefinition;
import org.mule.runtime.extension.api.annotation.ParameterGroup;
import org.mule.runtime.extension.api.annotation.param.Optional;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DmlOperations
{

    /**
     * Selects data from a database
     */
    //TODO: MetadataResolver needed to change to Iterator<Map> in case streaming is enabled.
    public List<Map<String, Object>> select(QueryDefinition queryDefinition,
                                            @Optional(defaultValue = "false") boolean streaming,
                                            @Optional(defaultValue = "10") int fetchSize,
                                            @Optional Integer maxRows,
                                            @ParameterGroup QuerySettings settings)
    {
        return new ArrayList<>();
    }

    /**
     * Inserts data into a database.
     *
     * @param queryDefinition
     * @param autoGeneratedKeyAttributes
     * @param bulkMode                   Indicates whether or not a bulk update is requested. When true, payload is required to be a
     *                                   collection and a bulk update executes for each item in the collection.
     */
    public int insert(QueryDefinition queryDefinition,
                      @ParameterGroup AutoGeneratedKeyAttributes autoGeneratedKeyAttributes,
                      @Optional(defaultValue = "false") boolean bulkMode,
                      @ParameterGroup QuerySettings settings)
    {
        return 0;
    }

    /**
     * Updates data in a database.
     *
     * @param queryDefinition
     * @param bulkMode        Indicates whether or not a bulk update is requested. When true, payload is required to be a
     *                        collection and a bulk update executes for each item in the collection.
     */
    public int update(QueryDefinition queryDefinition, @Optional(defaultValue = "false") boolean bulkMode, @ParameterGroup QuerySettings settings)
    {
        return 0;
    }

    /**
     * Deletes data in a database.
     *
     * @param queryDefinition
     * @param bulkMode        Indicates whether or not a bulk update is requested. When true, payload is required to be a
     *                        collection and a bulk update executes for each item in the collection.
     */
    public int delete(QueryDefinition queryDefinition, @Optional(defaultValue = "false") boolean bulkMode, @ParameterGroup QuerySettings settings)
    {
        return 0;
    }

    public Map<String, Object> storedProcedure(QueryDefinition queryDefinition, @ParameterGroup QuerySettings settings) {
        return new HashMap<>();
    }
}
